odk-x/docs

odkx-src/injected-interfaces-methods.rst
odkx-src/scan-install.rst
odkx-src/services-install.rst
odkx-src/survey-install.rst
odkx-src/tables-install.rst

closes ODK-X issue 156
addresses #
Fixed the OI file manager links since not in play store
Also fixed some spelling issues that came up when checking in the injected-interfaces-methods-rst by making spellings acceptable for that page

Testing revised setup by fixing OI file manager links and spelling fixes

---

odkx-src/injected-interfaces-methods.rst
odkx-src/scan-install.rst
odkx-src/services-install.rst
odkx-src/survey-install.rst
odkx-src/tables-install.rst
odkx-src/xlsx-converter-reference.rst

closes #
addresses 38 and 37 of ODK-X issues. 
Documentation of string(len) and choices should be at tableid===formid from issues prioritisation on TSC call 2020.04.22
At some point would be great to more fully document elementType and also to make it so you can't have contradictory choices.

Strings n choices documentation

---

odkx-src/index.rst
odkx-src/injected-interfaces-methods.rst
odkx-src/reference-apps.rst
odkx-src/scan-install.rst
odkx-src/select-tool-suite.rst
odkx-src/services-install.rst
odkx-src/survey-install.rst
odkx-src/survey-sample-app.rst
odkx-src/tables-install.rst
odkx-src/tables-sample-app.rst
odkx-src/xlsx-converter-reference.rst

addresses ODK-X issue 140 (and overall goal of improving learning paths)
Moved up the new "getting started" components and example/sample apps as initial step of reorganizing towards easy/clear learning paths.
Lots more to do! Still working away on updating the server etc. within the sample survey app. also need to create more of a how to get started intro. What is currently in "getting started"s needs to get cut/relocated. Will keep working on this on Friday.

Start of reorg. for learning paths

---

odkx-src/survey-sample-app-install.rst

Fixes the bad (style error) quotes from the previous version of this branch. 
Style check is not documented.

Fixed the bad quotes from the last try.

---

odkx-src/xlsx-converter-reference.rst

Fix some typos on XLSX converter docs

---

shared-src/docs-tech-guide.rst

closes #
addresses #19 
Deleted the style check outline part with no content and updated to cover checks more broadly. Also added a lot of -X, fixed the line edits link to ODK-X. 
We do need to delete all the ODK(1) related parts of the docs. I think we can also delete the text about the shared parts since they checked with the odkx checks too.

Fixed docs info about spell and style checks and added a lot of -X

---

odkx-src/sync-endpoint-cloud-setup.rst

Fixes style issues so documents build

fix spacing issues

---

odkx-src/sync-endpoint-cloud-setup.rst

fix spacing above last error (thought it would only be after the first error)

fix spacing issues 

---

odkx-src/index.rst
odkx-src/sync-endpoint-cloud-setup.rst
odkx-src/sync-endpoint-manual-setup.rst
odkx-src/sync-endpoint.rst

Fix build and style errors

---

odkx-src/sync-endpoint-cloud-setup.rst
odkx-src/sync-endpoint.rst

fix spelling errors

---

odkx-src/basics-install.rst
odkx-src/sync-endpoint-cloud-setup.rst
odkx-src/sync-endpoint.rst

Added minimum Android tablet version and fixed some spell checks
addresses Forum post: https://forum.odk-x.org/t/odk-x-table-android-version-support/780
Added minimum Android tablet version and fixed some spell checks

Adding minimum Android tablet version and fixed some spell checks

---

odkx-src/suitcase-intro.rst

closes #171
Documents the ODK-X Suitcase features for uploads (update, delete, new, etc.) and CSV structure needed. 
We could add screenshots, but I *think* the content is all there. 
I think I got the right formatting for the different buttons v. file names v. column headers but good for someone to check. In updating my version of sphinx a ton of files changed; I think I avoided staging and pushing them but there may be some issues around what is getting updated in various locations.

Updating suitcase documentation.

---

.circleci/config.yml

This PR will hopefully the deploy problem to s3

pin ruby to 2.7.2 to fix build

---

odkx-src/xlsx-converter-using.rst

Fixes 3 typos in xlsx-converter-using.rst

Fix 3 typos in xlsx-converter-using.rst

---

odkx-src/tables-sample-app-install.rst
odkx-src/tables-sample-app-jgi.rst

Addresses issue 123, "Create an Easy to Install Tables Demo App"
https://github.com/odk-x/tool-suite-X/issues/123
tables-sample-app-install.rst
Update to Tables demo server URL and credentials. 
tables-sample-app-jgi.rst
Minor edit to the JGI page. 
None
None
Server configuration failure, which is further described in the issue. This is an error covered by another issue, so not required to be solved in this PR.

Updates to Tables demo docs

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
odkx-src/conf.py
odkx-src/docs-tech-guide.rst

This PR updates the Pull Request template to remove the requirement for PRs to reference an open issue.
This PR also updates issue queue URL to https://github.com/odk-x/tool-suite-X/issues.

Update for new issue queue

---

odkx-src/docs-tech-guide.rst

closes odk-x/tool-suite-X#208
Changed url to direct to odk-x/tool-suite-X#207

Fix odk-x/tool-suite-X#208: Change line edit issue url to direct to #207

---

odkx-src/_templates/footer.html

Fix anchor bug on Chrome

---

odkx-src/conf.py

addresses odk-x/tool-suite-X#204

Update forum name in docs #204

---

odkx-src/suitcase-intro.rst

addresses odk-x/tool-suite-X#53
Includes improved documentation for both Suitcase GUI and Suitcase CLI.

Improved suitcase docs

---

odkx-src/app-designer-prereqs.rst
odkx-src/spelling_wordlist.txt

The app-designer setup instructions were out of date. Update to latest versions of upgraded software.

update app designer prereqs

---

odkx-src/basics-install.rst
requirements.txt

The install instructions were updated with respect to Android 10 whilst providing information about previous versions.

Updated install instructions

---

odkx-src/sync-endpoint-cloud-setup.rst
odkx-src/sync-endpoint-manual-setup.rst

addresses odk-x/tool-suite-X#224
Contains documentation for setup & enabling/disabling anonymous access for Sync Endpoint Manual Setup.
Documenting anonymous access for Sync Endpoint with Cloud services.

Documented anonymous access

---

odkx-src/sync-endpoint-manual-setup.rst

Hi @linl33 ,sorry I make another mistake here. I have corrected the numbering. Please review

Correct error in numbering

---

odkx-src/basics-install.rst

addresses odk-x/tool-suite-X#252
Fixed Android emulator broken links

Fix Android emulator broken links

---

odkx-src/build-app.rst

Addresses odk-x/tool-suite-X#248
Documentation on how to update versions of the app-designer software

update versions of app-designer

---

odkx-src/survey-using.rst

addresses odk-x/tool-suite-X#256
Updated the minimum Android version for Survey in docs.

Updated minimum Android version for Survey

---

.gitattributes
odkx-src/img/survey-using/Name.jpg
odkx-src/img/survey-using/TableID.jpg
odkx-src/spelling_wordlist.txt
odkx-src/survey-using.rst

closes odk-x/tool-suite-X#250
addresses odk-x/tool-suite-X#250
This is the documentation written for ordering the forms list according to the sort options given. The documentation is written using sphinx tools and the relevant screen short are also added at required place

document to sort the forms list

---

README.md

Fixed typo and article usage in README

Fix typo and article usage in README

---

odkx-src/aggregate-tables-extension.rst

closes [odk-x/tool-suite-X#265](https://github.com/odk-x/tool-suite-X/issues/265)
Added deprecation warning to Aggregate Extenstion directions to the documentation

Add deprecation warning to Aggregate Extenstion directions

---

odkx-src/img/services-managing/services-login-qr.png
odkx-src/img/services-managing/services-server-settings.png
odkx-src/services-managing.rst
odkx-src/survey-sample-app-install.rst
odkx-src/tables-sample-app-install.rst

closes odk-x/tool-suite-X#199
- Documented about the login with QR code feature of the Services app.
- Added a image for showing the QR icon on server settings fragment.
- Mentioned about this in other places like survey sample app install and tables sample app install.

Documented login with QR code

---

odkx-src/sync-endpoint-manual-setup.rst

updated the common issue of conflicting ports .
closes odk-x/tool-suite-X# https://github.com/odk-x/tool-suite-X/issues/266
Will be helpful for beginners to setup

update sync point - common issue

---

odkx-src/cold-chain-intro.rst

1. Fixed typo in cold chain intro page of the docs.

#207 - Fix typo in cold chain intro page

---

odkx-src/app-designer-prereqs.rst

addresses odk-x/tool-suite-X#223
This PR includes the changes made during the review of https://github.com/odk-x/tool-suite-X/issues/172 PR. I have updated the link to Java for Mac, how to check whether npm is installed properly on windows and addressed to install full Android Studio.

Updated information

---

odkx-src/app-designer-prereqs.rst
odkx-src/build-app.rst

addresses odk-x/tool-suite-X#144
Added a few grunt commands as suggested by @wbrunette, namely adbpull, adbpush and adbpull-logs

Updated grunt commands

---

odkx-src/scan-intro.rst

closes odk-x/tool-suite-X#272
1. Update scan intro documentation to reflect the state of the project (project has not been upgraded in a couple of years).
2. Request for project maintainers.

#272 - Update ODK-X Scan docs with warning/request for maintainer

---

odkx-src/sync-endpoint-manual-setup.rst

What is included in this PR?
There was an error in step numbering that has been corrected.
git clone command for sync-endpoint is modified to perform shallow clone.

Modify git clone to perform shallow clone

---

odkx-src/sync-endpoint.rst

closes odk-x/tool-suite-X#142
Documentation for sync client

document sync client

---

odkx-src/index.rst
odkx-src/trouble-shooting.rst

closes odk-x/tool-suite-X#282
1. Added a Trouble-shooting section to the documentation.
None

Add troubleshooting section to the documentation

---

odkx-src/contributing-tips.rst
odkx-src/docs-tech-guide.rst

1. Remove deprecated opendatakit-bot reference in contributing section.

Remove opendatakit-bot from contribution guide

---

odkx-src/_templates/layout.html
odkx-src/_templates/search.html

closes odk-x/tool-suite-X#287
1. Integrate Google Custom Search Engine in documentation. 
Hopefully, none.
Nothing.
None.

Integrate google custom search engine in the docs

---

LICENSE.md
odkx-src/app-designer-launching.rst
odkx-src/basics-install.rst
odkx-src/build-app.rst
odkx-src/cold-chain-tour.rst
odkx-src/conf.py
odkx-src/hope-study-tour.rst
odkx-src/index.rst
odkx-src/select-tool-suite.rst
odkx-src/tables-sample-app-custom-home.rst
odkx-src/tables-sample-app-install.rst
odkx-src/tables-sample-app-plot.rst

1. Minor line edits and updated License information.

Cross-reference and line edits

---

odkx-src/tables-sample-app-install.rst

Adds a notice for users if they stumble upon a merge conflict when installing the sample table application.

Add note for merge conflicts in installing sample

---

odkx-src/xlsx-converter-using.rst

1. Add Skip Logic section to XLSX Converter in ODK-X Documentation.

Add Skip Logic section to xlsx converter reference

---

.circleci/config.yml

Fix CircleCI apt-get update issue.

Allow apt-get release info change in circleci

---

odkx-src/img/sync-endpoint/endpoint-docker-swarm.png
odkx-src/sync-endpoint.rst

1. Add overview section to sync-endpoint

Add overview section to sync-endpoint

---

odkx-src/img/setup-digital-ocean/create-droplet.png
odkx-src/img/setup-digital-ocean/do-authentication.png
odkx-src/img/setup-digital-ocean/do-console-terminal.png
odkx-src/img/setup-digital-ocean/do-console.png
odkx-src/img/setup-digital-ocean/do-datacenter.png
odkx-src/img/setup-digital-ocean/do-distribution.png
odkx-src/img/setup-digital-ocean/do-droplets.png
odkx-src/img/setup-digital-ocean/do-networking.png
odkx-src/img/setup-digital-ocean/do-plan.png
odkx-src/img/setup-digital-ocean/do-userdata.png
odkx-src/img/setup-digital-ocean/do-userdata2.png
odkx-src/img/setup-digital-ocean/do1.png
odkx-src/img/setup-digital-ocean/do2.png
odkx-src/img/setup-digital-ocean/do3.png
odkx-src/img/setup-digital-ocean/do4.png
odkx-src/sync-endpoint-cloud-setup.rst

closes odk-x/tool-suite-X#292
1. Updated instruction for setting up a droplet (server) on the Digital Ocean platform
None
None
None

Update Digital Ocean instruction for Sync Endpoint with Cloud Services

---

odkx-src/img/survey-sample-app/survey-password-settings.png
odkx-src/img/survey-sample-app/survey-server-settings.png
odkx-src/img/survey-sample-app/survey-server-url.png
odkx-src/img/survey-sample-app/survey-signon-credential.png
odkx-src/img/survey-sample-app/survey-successful-authentication.png
odkx-src/img/survey-sample-app/survey-sync-success.png
odkx-src/img/survey-sample-app/survey-username-settings.png
odkx-src/survey-sample-app-install.rst

closes odk-x/tool-suite-X#143
I improved the documentation for authentication and syncing by making some changes to the text and adding descriptive screenshots which would help end users understand the processes better.

Improved documentation for authentication and syncing 

---

odkx-src/survey-using.rst

Fix odk x survey typo

---

odkx-src/index.rst

Line edits in documentation homepage

fix home page typo

---

odkx-src/build-app.rst
odkx-src/img/app-designer-overview/odk-x-debugging.png

closes odk-x/tool-suite-X#303
Documentation on how to debug ODK-X tables WebView.

Document debugging for ODK-X tables WebView.

---

odkx-src/build-app.rst

1. Remove reference to grunt file for tables as it is currently not working
2. Add Skip logic table as List and Detail view example
none
none
none

Update build app page

---

odkx-src/sync-endpoint.rst

This PR adds some more information about HTTPS and TLS/SSL encryption in sync-endpoint.rst file.

Https Content Addition

---

odkx-src/sync-endpoint-user-instructions.rst
odkx-src/sync-endpoint.rst

Please check if the issue resolves

#335 Missing reference label fixed

---

odkx-src/services-managing.rst

Signed-off-by: Sukriti-sood <soodsukriti1111@gmail.com>
closes odk-x/tool-suite-X [#317](https://github.com/odk-x/tool-suite-X/issues/317)
CC: @wbrunette

typo fixed

---

README.md

Addresses odk-x/tool-suite-X #408
[OUTREACHY SPRING 2023 STARTER ISSUE #3 - Do this third #408](https://github.com/odk-x/tool-suite-X/issues/408)
Updated ODK-X Docs regarding Docker setup, added more clarification on certain aspects of the documentation about virtualization on Windows and building the Docker image.

Updated ODK-X Docs on Docker Desktop setup.

---

README.md

closes [odk-x/tool-suite-X#408](https://github.com/odk-x/tool-suite-X/issues/408)
* added the forking of repo part
* updated the explanation of `docker build -t odkx-docs .`
* removed unnecessary info

updated README.md to be more user friendly

---

Dockerfile
odkx-src/survey-sample-app-overview.rst

closes odk-x/tool-suite-X#
Dockerfile clarifies the specific python version: 3.9.16
Update survey-sample-app-overview.rst by changing the 6 sample forms to table comparison view.

Update survey-sample-app-overview.rst & Dockerfile python version

---

Dockerfile
odkx-src/basics-install.rst

Addresses odk-x/tool-suite-X#  https://github.com/odk-x/tool-suite-X/issues/408
Improved a sentence in the "Required" section of "Installing ODK-X Basic Tools" because the sentence may be unclear or hard to follow.

Improved basics-install docs to provide clarity.

---

README.md

closes odk-x/tool-suite-X#
I modified the project cloning process to align with the basic procedure of cloning a repo for contribution

Project cloning process

---

odkx-src/build-app.rst
odkx-src/docs-developer-guide.rst
odkx-src/docs-tech-guide.rst

closes odk-x/tool-suite-X[#427](https://github.com/odk-x/tool-suite-X/issues/427)
This PR fixes some broken links encountered in the documentation

fixed broken links

---

odkx-src/build-app.rst
odkx-src/build-scripts.rst
odkx-src/cold-chain-tour.rst
odkx-src/contributing-tips.rst
odkx-src/docs-developer-guide.rst
odkx-src/hope-study-tour.rst
odkx-src/injected-interfaces.rst
odkx-src/logging-capabilities-of-apps.rst
odkx-src/notify-install.rst
odkx-src/services-internals.rst
odkx-src/suitcase-intro.rst
odkx-src/sync-endpoint-cloud-setup.rst
odkx-src/sync-endpoint-manual-setup.rst

closes odk-x/tool-suite-X[#428](https://github.com/odk-x/tool-suite-X/issues/428)
This PR includes improving link texts in the documentation for accessibility making them clearer and concise.

improve link texts in the documentation for accessibility and clarity

---

.circleci/config.yml

Fixes the deployment stage of the circle ci pipeline...
There are still some issues that I will try to fix in a later PR, but for now this should fix the immediate problems :-)

Build pipe fix

---

odkx-src/basics-install.rst

This PR fixes RST syntax to display 2 links properly on the Basic Install page.

fixed rst syntax for a link

---

odkx-src/survey-sample-app-overview.rst

- I made line-edits by fixing the typos in survey-sample-app-overview.rst which is for [odk-x/tool-suite-X/issues/207](https://github.com/odk-x/tool-suite-X/issues/207)
- Fixed and changed the typo `select prompt` to `select widgets`

Updated survey-sample-app-overview.srt

---

README.md

- The PR is intended to simplify the process of cloning a repository. It gives a clear and concise step by step guide to enhance user friendly experience particularly for persons who are cloning a repo for the first time.
- I modified the README file to provide clarity on cloning a repo.
- The instruction provided was tested on a local machine to verify their accuracy.

Repo-Clone-Update  on README.md

---

src/_static/css/custom.css
src/_templates/layout.html

A custom announcement banner to be displayed at the top of every page of the documentation.

Added a custom banner

---

src/odk-datajs.rst
src/odk-surveyjs.rst
src/odk-tablesjs.rst

closes part of https://github.com/odk-x/tool-suite-X/issues/149
@wbrunette @elmps2018 I decided to create a new PR for this that includes all the split 3 files

Document odkdata, odktables, odksurvey javascript functions

---

README.md

closes odk-x/tool-suite-X#
Fix local URL

No "build" page so it gives a 404 error

---

src/build-app.rst

closes odk-x/tool-suite-X#
This pull request addresses grammatical errors in the documentation.
This pull request is related to issue #207.
Please review and provide feedback.

Fixed grammatical error in build-app.rst

---

src/build-app.rst

addresses odk-x/tool-suite-X207
Corrected directory, in the "build-app" documentation

wrong directory correction, in build-app documentation

---

src/basics-install.rst

Corrected punctuation and capitalization errors in basics-install.rst issue#207

Corrected punctuation and capitalization errors in basics-install.rst

---

src/app-designer-overview.rst

1. I made line-edits in `app-designer-overview.rst` which is for https://github.com/odk-x/tool-suite-X/issues/207
2. Updated to documentation for more clarity and easy understanding of detail-views and list-views

fix doc description in app-designer-overview

---

src/advanced-topics-architect.rst

This PR addresses odk-x/tool-suite-X#490

Index javascript function documentation

---

src/_templates/layout.html

- included link to forum post outlining how to get the new release
- addresses odk-x/tool-suite-X#491

Updated banner message re. Chrome error
