odk-x/docs

odkx-src/xlsx-converter-using.rst
This PR updates the `async_assign` documentation to include a step to update `templatePath` in `customPromptTypes.js`.
This PR also fixes a missing space on line 499.
=> Include templatePath update in async_assign doc

odkx-src/xlsx-converter-reference.rst, odkx-src/xlsx-converter-using.rst
This PR fixes validation tags examples. 
The tags should be defined in a space-separated list as specified in the [formDef.json documentation](https://docs.odk-x.org/formdef-structure/#sections-sub-component) and [implemented in XLSXConverter2](https://github.com/odk-x/app-designer/blob/7abf14b16d940850cedfa66e2f9c2afd79553b3e/xlsxconverter/XLSXConverter2.js#L1300-L1302).
=> Fix validation tags docs

odkx-src/sync-endpoint.rst
Fixes the link at the top of this page: https://docs.odk-x.org/sync-endpoint/ to the ODK-X REST Protocol.
=> Fix link to REST Protocol

odkx-src/xlsx-converter-reference.rst
Should be merged with release 2.1.7
This PR brings the date prompt types section of the docs up to date with with the latest changes in 2.1.7.
=> Add birth_date and update date_no_time prompttypes

run-task.bat
Add double quotes to run-task.bat file
After getting the `docker: invalid reference format` a few time after I ran `.\run-task.bat odkx-autobuild`. I got the idea to add quotes because there is a space in the file path `C:\Users\Temenu Esther-Phebe\odk\odk-x-docs>` . Adding single quotes `'%~dp0:/mnt'` to the run-task.bat file gave me the same output (`docker: invalid reference format`) while adding double quotes `"%~dp0:/mnt"`  started the build and serve process on **Windows 10 Pro, Version 20H2 (OS Build 19042.804)**
1. Change in run-task.bat file from `docker run --rm -v %~dp0:/mnt -p 8080:8080 --name odkx-docs odkx-docs %1` to double quotes around `"%~dp0:/mnt"` `docker run --rm -v "%~dp0:/mnt" -p 8080:8080 --name odkx-docs odkx-docs %1` 
There is a need to find out whether the …
=> Add double quotes to run-task.bat file

odkx-src/xlsx-converter-reference.rst, run-task.bat
Add signature prompt type and fix survey prompt type URL in docs docs
closes odk-x/tool-suite-X#174
1. URL [https://docs.odk-x.org/xlsx-converter-reference/#id4](https://docs.odk-x.org/xlsx-converter-reference/#id4) improved to [https://docs.odk-x.org/xlsx-converter-reference/#survey-prompt-types](https://docs.odk-x.org/xlsx-converter-reference/#survey-prompt-types) 
2. Signature prompt type and description added to Survey Prompt Types list.
I built and served the cloned repository with Docker, I noticed that when I ran `.\run-task.bat odkx-autobuild`  it returned  `docker: invalid reference format`. I was tinkering around in the `run-task.bat` file and found out that when I added double quotes around `'%~dp0:/mnt'` , the problem was solved. I spoke to the mentors and @wbrunette asked …
=> Fix #174: Add signature prompt type and fix survey prompt type URL in docs

odkx-src/app-designer-prereqs.rst
closes odk-x/tool-suite-X#118
1. Update documentation with the Android SDK and [ADB](https://developer.android.com/studio/command-line/adb.html) installation process with `command-line tools`.
=> Fix 118 - Update Android SDK and ADB installation in documentation

odkx-src/sync-endpoint-manual-setup.rst, odkx-src/sync-endpoint.rst
Whats included in this pr ?
Documentation for how to configure the defaults of OpenLDAP .
Documentation for how to use another LDAP UI to access the OpenLDAP .
Documentation for how to change Sync-Endpoint to use/access a different LDAP than the OpenLDAP in the Docker swarm .
Documentation for using LDAP utils .
Should fix https://github.com/odk-x/tool-suite-X/issues/145
=> Add documentaion for advanced configuration of LDAP

odkx-src/xlsx-converter-reference.rst
This PR updates the documentation for `hideInContents`. Pending a change in app-designer, `hideInContents` will be able to take a JavaScript expression and conditionally hide contents.
odk-x/app-designer#145
=> Update hideInContents docs

odkx-src/contributing-tips.rst
1. Remove "**writing @opendatakit-bot claim**" as a way to claim issues in contribution tips documentation. This is removed because it is old and no longer works.
=> Update claim issue section to remove old documentation - #207

odkx-src/xlsx-converter-reference.rst
closes odk-x/tool-suite-X#152
addresses odk-x/tool-suite-X#152
It includes the prompt for the text area if we go above 255 characters. I have added the way to increase the character limit by adding the note there
Please tell me if I left anything or what more it requires.
Thank you!!
=> documented prompt Text area

odkx-src/index.rst, odkx-src/sync-endpoint-cloud-setup.rst, odkx-src/sync-endpoint-user-instructions.rst, odkx-src/sync-endpoint.rst
addresses odk-x/tool-suite-X#263
Created a new documentation file to consolidate sync-endpoint user instructions into its own section under sync endpoint.
Moved the instruction for creating users, creating groups, assigning groups, and creating sample users from https://docs.odk-x.org/sync-endpoint/#creating-groups and https://docs.odk-x.org/sync-endpoint-cloud-setup/#creating-a-sample-user  to the new file.
=> Sync endpoint user instruction

odkx-src/app-designer-prereqs.rst, odkx-src/spelling_wordlist.txt
Running "sdkmanager" on mac requires a "./" prefix. E.g: `./sdkmanager [args]`. Users who are not familiar with scripting or programming may not know this. The instructions say to run sdkmanager by using the command `sdkmanager [args]` or `sdkmanager.bat [args]`, so this change will help clarify that.
=> Clarify command in app-designer-prereqs.rst

odkx-src/docs-tech-guide.rst
Fixed typo in the setup collaboration accounts section of docs contributor technical guide
Why haven't we mentioned about **Slack** here, and in the section `should I ask in the forum or a github issue` there are two parts mentioning `on Github` and `on Github issue`.  Are they suppose to be different? I guess one of them should have been slack.
=> fix typo in docs-contributor-technical-guide

odkx-src/aggregate-tables-extension.rst, odkx-src/cloud-endpoints-intro.rst, odkx-src/index.rst, odkx-src/scan-data.rst, odkx-src/scan-install.rst, odkx-src/scan-intro.rst, odkx-src/scan-managing.rst, odkx-src/scan-using.rst
closes odk-x/tool-suite-X#279
1. Adding Deprecated and Currently Not Supported section to the Documentation TOC tree and 
2. Move the Scan section to Currently Not Supported and Aggregate Tables extension to Deprecated
None that I could think of.
I need feedback on the problem stated below.
I added the Deprecated and Currently Not supported to the docs toctree, moved the page file names for scan and aggregate tables extension in the index.rst file and served it locally on my PC.
When it’s on the home page (index), it’s fine and the newly added section show up. When I click the aggregate tables link (under Deprecated), it reverts back to the cloud endpoints section. I edited the section labels for the pages and it didn’t revert but when I click any other link from the Docs sidebar TOC, the …
=> #279 - Add deprecated and currently not supported section in docs

odkx-src/build-scripts.rst
addresses odk-x/tool-suite-X#284
1. Information on signature keys for building the Android Tools 
Add this information to the android tools GitHub README
=> Add signature key to build scripts section in docs

odkx-src/app-designer-overview.rst
addresses odk-x/tool-suite-X#286
1. Add information about [Object SQLError] to the Purge Database, App designer section of the documentation.
1. A fix that shows a clear, understandable error message instead  of the vague [Object SQLError] prompt.
None.
=> Add information about Object SQL Error to App designer preview section

odkx-src/_templates/search.html
1. After [https://github.com/odk-x/docs/pull/130](https://github.com/odk-x/docs/pull/130) was merged, I noticed that I left a trailing string in the code when I tested it out. This PR fixes that.
=> Line edit in search results page

odkx-src/sync-endpoint-manual-setup.rst
closes odk-x/tool-suite-X#104
Added a link to a README file to find the minimum compatible versions of MySQL, PosgreSQL, and MSSQL so users know which databases to use when setting up the Sync-Endpoint locally.
=> Document Sync-Endpoint is compatible with what DB version

odkx-src/xlsx-converter-reference.rst
closes odk-x/tool-suite-X#289
Update prompt types documentation to include
1. Year only prompts
2. Month only prompts
3. Year and month only
4. Non-gregorian calendar date pickers.
None
None
None
=> Update prompt types documentation with new date prompt types

odkx-src/basics-install.rst, odkx-src/getting-started-2-architect.rst, odkx-src/scan-install.rst, odkx-src/scan-managing.rst, odkx-src/services-managing.rst, odkx-src/survey-using.rst, odkx-src/tables-managing.rst
closes odk-x/tool-suite-X#297
Removed OI file manager from requirements as it is no longer required for the upcoming version 2.1.9 .
=> Remove OI File Manager requirement from documentation

odkx-src/sync-endpoint-user-instructions.rst
This PR makes some amendments in the "create users" page of Sync - Endpoint. The creating users instructions were written twice and hence it was merged into one.
=> Create users and groups - Sync Endpoint

.circleci/config.yml, src/conf.py
This PR updates the read the docs template to use correct "Edit on GitHub" url...
=> Fixes related to branch renaming

src/conf.py
Updated sphinx conf to reflect folder structure change from "odkx-src" to simply "src"
(sorry I missed this first time around - this should have been included in #262 )
=> Edit on GitHub path fix

Dockerfile, Makefile, README.md, run-task.bat, run-task.ps1, run-task.sh
- Added "dockerserve" task to Makefile, overriding sphinx-autobuild to bind to 0.0.0.0:8080 instead of default 127.0.0.1:8000
- Updated the Dockerfile to build on latest python image (3.12.1) and changed entrypoint to include the "dockerserve" command to simplify usage in run-task scripts
- Updated run-task scripts to not use command line args
- Migrated from legacy cmd `.bat` script to `.ps1` powershell to align with README instructions
- Updated README.md to reflect changes
- Windows
- MacOS
- CTRL+C (and CTRL+P CTRL+C) does not detach from the docker container (due to the ENTRYPOINT being the "make" command, I believe). Tried to fix it, but couldn't find a consistently working fix across mac and windows - so I updated the README instead to reflect that the `docker stop` command must be …
=> Fixing docker issues

run-task.ps1
The port number in the ps1 file is incorrect - it should be 8080 to match what the container exposes.
(it is correct in the equivalent .sh file used on macOS)
=> Fixed port number in docker command 

src/notify-install.rst
Pull Request releted to [issue#471](https://github.com/odk-x/tool-suite-X/issues/471)
The broken hyperlink issue has been resolved not only in the "guide" hyperlink mentioned previously but also in another location within the documentation. Specifically, in the passage discussing the Firebase setup, there was also a broken link. The problematic link was within the sentence: "Place the 'google-services.json' file obtained from step 8 of the Firebase setup under the 'sdcard/opendatakit/default/config/assets/' directory
=> Fix issue 471

src/build-app.rst
1. Updated the `build-app.rst` doc and changed  `''?' + opendatakit.getHashString('testForm')` in the documentation to `''?' + odkSurvey.getHashString('testForm')`
2. Added `Note` section to run `framework.xlsx` through the XLSX Converter after making changes to the file.
=> updated the build app doc

src/contributing-tips.rst
This PR is realted to the [issue](https://github.com/odk-x/tool-suite-X/issues/207)
Corrected punctuation, grammar, and capitalization errors in contributing-tips.rst file .
=> fixing the typo error in contributing-tips.rst
